<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Title>NoSoliciting.Plugin</Title>
		<Authors>Anna,kalilistic,Noevain</Authors>
		<Version>3.1.10.0</Version>
		<Platforms>x64</Platforms>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<Deterministic>true</Deterministic>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<Configurations>Debug;Release</Configurations>
		<AssemblyName>NoSoliciting</AssemblyName>
		<RootNamespace>NoSoliciting</RootNamespace>
		<PackageVersion>$(Version)</PackageVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<NoWarn>CS1591</NoWarn>
	</PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Fody" Version="6.8.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.ML" Version="2.0.1"/>
        <PackageReference Include="Resourcer.Fody" Version="1.8.1" PrivateAssets="all"/>
        <PackageReference Include="YamlDotNet" Version="13.4.0"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Resources\Language.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Language.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\NoSoliciting.Interface\NoSoliciting.Interface.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Resources\Language.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>NoSoliciting.resx</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
